---
# ansible_user: "ec2-user"
ansible_python_interpreter: "auto_silent"
# ansible_ssh_private_key_file: "files/ssh-key.pem"

# AWS 
aws_ssh_key_pair: "ansible-labs-only"
instance_type: "t3a.small"
region: "us-east-2"
security_group: "ssh-http-https"
vpc_subnet: "subnet-3964a275"
...
