---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
  - name: CREATE NODES
    bigip_node:
      provider:
        server: "{{ ansible_host }}"
        user: "{{ f5_username }}"
        password: "{{ f5_password }}"
        server_port: 8443
        validate_certs: false
      host: "{{ hostvars[item].private_ip }}"
      name: "{{ hostvars[item].inventory_hostname }}"
    loop: "{{ groups['webservers'] }}"
...
