---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
  - name: CREATE POOL
    bigip_pool:
      provider:
        server: "{{ ansible_host }}"
        user: "{{ f5_username }}"
        password: "{{ f5_password }}"
        server_port: 8443
        validate_certs: false
      name: "http_pool"
      lb_method: "round-robin"
      monitors: "/Common/http"
      monitor_type: "and_list"
...
