---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
  - name: ADD POOL MEMBERS
    bigip_pool_member:
      provider:
        server: "{{ ansible_host }}"
        user: "{{ f5_username }}"
        password: "{{ f5_password }}"
        server_port: 8443
        validate_certs: false
      state: "present"
      name: "{{ hostvars[item].inventory_hostname }}"
      host: "{{ hostvars[item].private_ip }}"
      port: "80"
      pool: "http_pool"
    loop: "{{ groups['webservers'] }}"
...
