---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
  - name: ADD VIRTUAL SERVER
    bigip_virtual_server:
      provider:
        server: "{{ ansible_host }}"
        user: "{{ f5_username }}"
        password: "{{ f5_password }}"
        server_port: 8443
        validate_certs: false
      name: "vip"
      destination: "{{ private_ip }}"
      port: "443"
      enabled_vlans: "all"
      all_profiles: ['http', 'clientssl', 'oneconnect']
      pool: "http_pool"
      snat: "Automap"
...
