---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
  - name: SAVE RUNNING CONFIG ON BIG-IP
    bigip_config:
      provider:
        server: "{{ ansible_host }}"
        user: "{{ f5_username }}"
        password: "{{ f5_password }}"
        server_port: 8443
        validate_certs: false
      save: true
...
