---
- name: AS3
  hosts: lb
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "tenant_name"
      prompt: "Enter the Tenant name:"
      private: no
      default: "WorkshopExample"

  tasks:
  - name: Remove Tenant AS3
    uri:
      url: "https://{{ ansible_host }}:8443/mgmt/shared/appsvcs/declare/{{ tenant_name }}"
      method: DELETE
      status_code: 200
      timeout: 300
      body_format: json
      force_basic_auth: true
      user: "{{ f5_username }}"
      password: "{{ f5_password }}"
      validate_certs: false
...
