---
- name: "Create host instances."
  hosts: localhost
  gather_facts: false
  vars:
    aws_profile: "{{ lookup('env', 'AWS_PROFILE') }}"
    siduser: "{{ lookup('env', 'MYSIDLABS_USER') }}"

  roles:
    - env_check

  tasks:

    - name: "Provision and launch instances"
      ec2:
        assign_public_ip: true
        group: "{{ security_group }}"
        image: "ami-01e36b7901e884a10"
        instance_tags:
          Name: "{{ siduser }}-{{ item.tier }}-{{ idx }}"
          mysidlabs: "1"
          mysidlabs-cost: "ephemeral"
          mysidlabs_owner: "{{ siduser }}"
          mysidlabs_tier: "{{ item.tier }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ aws_ssh_key_pair }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet }}"
        wait: true
        volumes:
        - device_name: /dev/sda1
          delete_on_termination: true
          volume_size: 8
          volume_type: standard
      loop:
        - { tier: "lb" }
        - { tier: "web" }
        - { tier: "web" }
      loop_control:
        index_var: idx
      register: result

    # Note that we're not doing anything with an inventory here.
    # In Lab1, we had the playbook also create the static 
    # inventory.  In this lab, we'll be using a dynamic inventory.

    - debug:
        msg: "{{ item.instances[0].tags.Name }} == Private IP: {{ item.instances[0].private_ip }}, Public IP: {{ item.instances[0].public_ip }}"
      loop: "{{ result.results }}"
      loop_control:
        label: ""
...
