---
- name: BIG-IP SETUP
  hosts: tag_Group_qs_lb
  connection: local

  tasks:
  - name: Setup provider
    set_fact:
      provider:
        server: "{{ ansible_host }}"
        user: "{{ machine.username }}"
        password: "{{ machine.password }}"
        server_port: "8443"
        validate_certs: "no"

  - name: Call Node Role
    include_role:
      name: f5-nodes
...
