---
#- name: "Confirm proper owner"
#  assert:
#    that:
#      - "tag_mysidlabs_owner == siduser"
#    fail_msg: "Host is not owned by {{ siduser }}"

- name: Enable EPEL repository
  become: true
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install nginx
  become: true
  yum:
    name: nginx
    state: present
    update_cache: yes

- name: Build nginx Configuration
  become: true
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Restart nginx Service
  become: true
  service:
    name: nginx
    state: restarted
...
