---

- name: "Cleanup all instances that match the target tag - mysidlabs_owner: {{ siduser }}"
  hosts: localhost
  gather_facts: false

  tasks:

    - name: "Terminate labeled instances"
      ec2_instance:
        region: "{{ region }}"
        state: absent
        wait: false
        filters:
          "tag:mysidlabs_owner": "{{ siduser }}"
          "tag:mysidlabs": "1"
...
