---
# tasks file for f5-nodes
- name: CREATE NODES
  bigip_node:
    provider: "{{ provider }}"
    host: "{{ hostvars[item].ec2_private_ip_address }}"
    name: "{{ hostvars[item].ec2_tag_Name }}"
  loop: "{{ groupName }}"
...