---
# tasks file for f5-nodes
- name: CREATE NODES
    bigip_node:
      provider:
        server: "{{ ansible_host }}"
        user: "{{ f5_username }}"
        password: "{{ f5_password }}"
        server_port: 8443
        validate_certs: false
      host: "{{ hostvars[item].private_ip }}"
      name: "{{ hostvars[item].inventory_hostname }}"
    loop: "{{ webservers }}"
...