---
- name: Install Apache
  become: true
  yum:
    name: httpd
    state: present
    update_cache: yes

- name: Configure Apache index.html
  become: true
  template:
    src: index.html
    dest: /var/www/html/index.html

- name: Start Apache Service
  become: true
  service:
    name: httpd
    state: started
...
