---
- name: Install Apache
  become: true
  yum:
    name: httpd
    state: present
    update_cache: yes

- name: Configure Apache index.html
  become: true
  template:
    src: index.j2
    dest: /var/www/html/index.html

- name: Copy images
  become: true
  copy:
    src: files/{{ ec2_tag_Name }}.png
    dest: /var/www/images/

- name: Start Apache Service
  become: true
  service:
    name: httpd
    state: started
...
