---
- name: Install Apache
  become: true
  yum:
    name: httpd
    state: present
    update_cache: yes

- name: Configure Apache index.html
  become: true
  template:
    src: index.j2
    dest: /var/www/html/index.html

- name: Copy images
  become: true
  copy:
#    src: files/{{ ec2_tag_Name }}.png
    src: files/{{ item }}
    dest: /var/www/html/
    mode: u=rw,g=r,o=r
  loop:
    - F5-QS-Demo-web1.png
    - F5-QS-Demo-web2.png
    - F5-QS-Demo-web3.png

#- name: Change directory permissions
#  become: true
#  file:
#    path: /var/www/images/
#    state: directory
#    mode: u=rw,g=r,o=r

- name: Start Apache Service
  become: true
  service:
    name: httpd
    state: restarted
...
