---
- name: Cleanup F5
  hosts: tag_lb
  connection: local

  tasks:
  - name: Setup provider
    set_fact:
      provider:
        server: "{{ ansible_host }}"
        server_port: "8443"
        validate_certs: "False"

  - name: Call Cleanup Role
    include_role:
      name: cleanup
...
