---
- name: AS3
  hosts: tag_lb
  connection: local
  gather_facts: false

  vars:
    poolMembers: "{{ groups['webservers'] }}"

  tasks:
    - name: Push AS3
      uri:
        url: "https://{{ ansible_host }}:8443/mgmt/shared/appsvcs/declare"
        method: POST
        body: "{{ lookup('template','as3_template_waf.j2', split_lines=False) }}"
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "admin"
        password: "Mys1dlabspw!"
        validate_certs: false
...
