---
- name: AS3
  hosts: lb
  connection: local
  gather_facts: false

  vars:
    pool_members: "{{ groups['webservers'] }}"

  vars_prompt:
    - name: "tenant_name"
      prompt: "Enter the Tenant name:"
      private: no
      default: "WorkshopExample"

  tasks:
    - name: Push AS3
      uri:
        url: "https://{{ ansible_host }}:8443/mgmt/shared/appsvcs/declare"
        method: POST
        body: "{{ lookup('template','30_as3_template.j2', split_lines=False) }}"
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ f5_username }}"
        password: "{{ f5_password }}"
        validate_certs: false
...
